# Generated by Django 5.2.4 on 2025-08-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('PlayerCards', models.TextField()),
                ('AiCard', models.TextField()),
                ('PlayerFinalCards', models.TextField()),
                ('AiFinalCards', models.TextField()),
                ('PlayerHandRank', models.CharField(max_length=50)),
                ('AiHandRank', models.CharField(max_length=50)),
                ('Choice', models.CharField(choices=[('strong', 'Strong'), ('weak', 'Weak')], max_length=10)),
                ('ChoiceBy', models.CharField(choices=[('player', 'Player'), ('ai', 'Computer')], max_length=10)),
                ('Winner', models.CharField(choices=[('player', 'Player'), ('ai', 'Computer'), ('draw', 'Draw')], max_length=10)),
                ('PlayerDice', models.IntegerField()),
                ('AiDice', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('EventType', models.CharField(choices=[('deal', 'Deal'), ('exchange', 'Exchange'), ('roll', 'Roll'), ('choice', 'Choice'), ('showdown', 'Showdown')], max_length=10)),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('GameId', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.PROTECT, to='app.game')),
            ],
            options={
                'db_table': 'gameLog',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='UserId',
            field=models.ForeignKey(db_column='Id', on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
    ]
