# Generated by Django 5.2.5 on 2025-08-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_cards', models.TextField()),
                ('ai_cards', models.TextField()),
                ('player_final_cards', models.TextField()),
                ('ai_final_cards', models.TextField()),
                ('player_hand_rank', models.CharField(max_length=50)),
                ('ai_hand_rank', models.CharField(max_length=50)),
                ('choice', models.CharField(choices=[('strong', 'Strong'), ('weak', 'Weak')], max_length=10)),
                ('choice_by', models.CharField(choices=[('player', 'Player'), ('ai', 'Computer')], max_length=10)),
                ('winner', models.CharField(choices=[('player', 'Player'), ('ai', 'Computer'), ('draw', 'Draw')], max_length=10)),
                ('player_dice', models.IntegerField()),
                ('ai_dice', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='플레이어', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('deal', 'Deal'), ('exchange', 'Exchange'), ('roll', 'Roll'), ('choice', 'Choice'), ('showdown', 'Showdown')], max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.PROTECT, to='app.game')),
            ],
            options={
                'db_table': 'log',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
    ]
